services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: bootcamp_2504
      PGDATA: /var/lib/postgresql/data/pgdata15
    networks:
      - bootcamp-network
    ports:
      - "5532:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"

  redis:
    image: redis:7
    container_name: redis-container
    networks:
      - bootcamp-network
    ports:
      - "6479:6379"
    volumes:
      - "./redis_data:/data"

  data-supplier-app:
    image: data-supplier:0.0.1
    container_name: data-supplier-app
    networks:
      - bootcamp-network
    ports:
      - "8100:8090"
      
  stock-data-app:
    image: stock-data:0.0.1
    container_name: stock-data-app
    networks:
      - bootcamp-network
    ports:
      - "8101:8091"

  ui-app:
    image: ui:0.0.1
    container_name: ui-app
    networks:
      - bootcamp-network
    ports:
      - "8102:8092"

volumes:
  redis_data:

networks:
  bootcamp-network:
    driver: bridge

