server:
  port: 8092

# DNS cloudflare domain for gcp
# BASE_URL: https://natureai.dpdns.org

# service:
#   coingecko:
#     host:
#       demo: "api.coingecko.com"
#       pro: "pro-api.coingecko.com"
#     api:
#       key-name: "x-cg-demo-api-key"
#       key-value: "CG-ZRR6HJgbqiMFjtYyqKYaCuTA"
#       markets:
#         version: "api/v3"
#         endpoint: "/coins/markets"

# Docker: postgres-container and redis-container

---
# ==========================================
# 基礎共用設定
# ==========================================
spring:
  profiles:
    active: ${EXTERNAL_IP:localhost}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

service:
  stock-data:
    host: ${STOCK_DATA_HOST:stock-data-app}
    port: ${STOCK_DATA_PORT:8091}
      
---
# ==========================================
# 本地環境設定（當 EXTERNAL_IP=localhost 時生效）
# ==========================================
spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgres-container:5432/bootcamp_2504"
    username: "postgres"
    password: "admin1234"

---
# ==========================================
# 雲端環境設定（當 EXTERNAL_IP=remote 時生效）
# ==========================================
spring:
  config:
    activate:
      on-profile: remote
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: ${SPRING_DATASOURCE_URL}
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"

service:
  stock-data:
    host: ${STOCK_DATA_HOST:stock-data-app}
    port: ${STOCK_DATA_PORT:80}


